ttl_default_sec: 86400

methods:
  mcp.purchase.basic:
    ttl_sec: 86400
    caps:
      - "store/write"
      - "topic/post"

  mcp.mint.ucan:
    ttl_sec: 3600
    caps:
      - "ucan/mint"

  data.fetch.readonly:
    ttl_sec: 300
    caps:
      - "data/fetch#read"
