name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci || npm i
      - run: npm run build || echo "no build step"
      - run: npx vitest run --coverage

  # Placeholder for Go interop; enable when fixtures & tool are added
  # interop:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.22.x'
  #     - run: |
  #         echo "TODO: go-ucan verify TS fixtures"
